### ISSUE TITLE
An error ocurred during the analysis

### ISSUE THREAD

**Issue by Funkster120** [n8felton/Firefox-ADMX#21]
The Following Error occurs after extending the "administrative templates":

The resource listed in the property "$(string.MOZILLA_FIREFOX_LOCKED_CUSTOM_USE.." could not be found. 

File C:\Windows\PolicyDefinitions\Mozilla.admx, row 40, column 341

![analysis](https://cloud.githubusercontent.com/assets/24548540/21146535/4f68b6c2-c152-11e6-8aa9-17c1d6e83a5a.PNG)

**Comment by dlfraga** [comment]
Hello,
Maybe this problem is happening because of some string that was not translated into german. Can you try to delete the de-DE/Mozilla.adml and test again?

**Comment by Funkster120** [comment]
hanelt@burkom.de


Am 25. Januar 2017 16:07:03 MEZ schrieb Daniel Fraga <notifications@github.com>:
>Hello,
>Maybe this problem is happening because of some string that was not
>translated into german. Can you try to delete the de-DE/Mozilla.adml
>and test again?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/n8felton/Firefox-ADMX/issues/21#issuecomment-275132045

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by n8felton** [comment]
Fixed with #24. Thanks to @91jme for the PR.

**Comment by Funkster120** [comment]
Didn't solve the problem in my case. Deleting the .adml file causes the error message to disappear but there is no Mozilla content in the GPO either.
